# Generated by Django 5.2.7 on 2025-10-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Question',
            new_name='qs',
        ),
    ]
