# Generated by Django 5.2.7 on 2025-10-27 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_rename_question_qs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='qs',
            new_name='Question',
        ),
    ]
